/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MainRouteImport } from './routes/main'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingIndexRouteImport } from './routes/billing/index'
import { Route as TestUserListRouteImport } from './routes/test/user-list'
import { Route as TestReferralLinkRouteImport } from './routes/test/referral-link'
import { Route as TestFormBuilderRouteImport } from './routes/test/form-builder'
import { Route as TestEmailEditorRouteImport } from './routes/test/email-editor'
import { Route as TestCampaignCardRouteImport } from './routes/test/campaign-card'
import { Route as TestAnalyticsDashboardRouteImport } from './routes/test/analytics-dashboard'
import { Route as OauthSignedinRouteImport } from './routes/oauth/signedin'
import { Route as BillingPlansRouteImport } from './routes/billing/plans'
import { Route as BillingPayment_methodRouteImport } from './routes/billing/payment_method'
import { Route as BillingPayment_attemptRouteImport } from './routes/billing/payment_attempt'
import { Route as BillingPayRouteImport } from './routes/billing/pay'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestUserListRoute = TestUserListRouteImport.update({
  id: '/test/user-list',
  path: '/test/user-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TestReferralLinkRoute = TestReferralLinkRouteImport.update({
  id: '/test/referral-link',
  path: '/test/referral-link',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFormBuilderRoute = TestFormBuilderRouteImport.update({
  id: '/test/form-builder',
  path: '/test/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const TestEmailEditorRoute = TestEmailEditorRouteImport.update({
  id: '/test/email-editor',
  path: '/test/email-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCampaignCardRoute = TestCampaignCardRouteImport.update({
  id: '/test/campaign-card',
  path: '/test/campaign-card',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAnalyticsDashboardRoute = TestAnalyticsDashboardRouteImport.update({
  id: '/test/analytics-dashboard',
  path: '/test/analytics-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSignedinRoute = OauthSignedinRouteImport.update({
  id: '/oauth/signedin',
  path: '/oauth/signedin',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPlansRoute = BillingPlansRouteImport.update({
  id: '/billing/plans',
  path: '/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPayment_methodRoute = BillingPayment_methodRouteImport.update({
  id: '/billing/payment_method',
  path: '/billing/payment_method',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPayment_attemptRoute = BillingPayment_attemptRouteImport.update({
  id: '/billing/payment_attempt',
  path: '/billing/payment_attempt',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPayRoute = BillingPayRouteImport.update({
  id: '/billing/pay',
  path: '/billing/pay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/articles': typeof ArticlesRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/email': typeof EmailRoute
  '/main': typeof MainRoute
  '/media': typeof MediaRoute
  '/signin': typeof SigninRoute
  '/webhooks': typeof WebhooksRoute
  '/billing/pay': typeof BillingPayRoute
  '/billing/payment_attempt': typeof BillingPayment_attemptRoute
  '/billing/payment_method': typeof BillingPayment_methodRoute
  '/billing/plans': typeof BillingPlansRoute
  '/oauth/signedin': typeof OauthSignedinRoute
  '/test/analytics-dashboard': typeof TestAnalyticsDashboardRoute
  '/test/campaign-card': typeof TestCampaignCardRoute
  '/test/email-editor': typeof TestEmailEditorRoute
  '/test/form-builder': typeof TestFormBuilderRoute
  '/test/referral-link': typeof TestReferralLinkRoute
  '/test/user-list': typeof TestUserListRoute
  '/billing': typeof BillingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/articles': typeof ArticlesRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/email': typeof EmailRoute
  '/main': typeof MainRoute
  '/media': typeof MediaRoute
  '/signin': typeof SigninRoute
  '/webhooks': typeof WebhooksRoute
  '/billing/pay': typeof BillingPayRoute
  '/billing/payment_attempt': typeof BillingPayment_attemptRoute
  '/billing/payment_method': typeof BillingPayment_methodRoute
  '/billing/plans': typeof BillingPlansRoute
  '/oauth/signedin': typeof OauthSignedinRoute
  '/test/analytics-dashboard': typeof TestAnalyticsDashboardRoute
  '/test/campaign-card': typeof TestCampaignCardRoute
  '/test/email-editor': typeof TestEmailEditorRoute
  '/test/form-builder': typeof TestFormBuilderRoute
  '/test/referral-link': typeof TestReferralLinkRoute
  '/test/user-list': typeof TestUserListRoute
  '/billing': typeof BillingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/articles': typeof ArticlesRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/email': typeof EmailRoute
  '/main': typeof MainRoute
  '/media': typeof MediaRoute
  '/signin': typeof SigninRoute
  '/webhooks': typeof WebhooksRoute
  '/billing/pay': typeof BillingPayRoute
  '/billing/payment_attempt': typeof BillingPayment_attemptRoute
  '/billing/payment_method': typeof BillingPayment_methodRoute
  '/billing/plans': typeof BillingPlansRoute
  '/oauth/signedin': typeof OauthSignedinRoute
  '/test/analytics-dashboard': typeof TestAnalyticsDashboardRoute
  '/test/campaign-card': typeof TestCampaignCardRoute
  '/test/email-editor': typeof TestEmailEditorRoute
  '/test/form-builder': typeof TestFormBuilderRoute
  '/test/referral-link': typeof TestReferralLinkRoute
  '/test/user-list': typeof TestUserListRoute
  '/billing/': typeof BillingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/analytics'
    | '/api-keys'
    | '/articles'
    | '/campaigns'
    | '/contacts'
    | '/deals'
    | '/email'
    | '/main'
    | '/media'
    | '/signin'
    | '/webhooks'
    | '/billing/pay'
    | '/billing/payment_attempt'
    | '/billing/payment_method'
    | '/billing/plans'
    | '/oauth/signedin'
    | '/test/analytics-dashboard'
    | '/test/campaign-card'
    | '/test/email-editor'
    | '/test/form-builder'
    | '/test/referral-link'
    | '/test/user-list'
    | '/billing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/analytics'
    | '/api-keys'
    | '/articles'
    | '/campaigns'
    | '/contacts'
    | '/deals'
    | '/email'
    | '/main'
    | '/media'
    | '/signin'
    | '/webhooks'
    | '/billing/pay'
    | '/billing/payment_attempt'
    | '/billing/payment_method'
    | '/billing/plans'
    | '/oauth/signedin'
    | '/test/analytics-dashboard'
    | '/test/campaign-card'
    | '/test/email-editor'
    | '/test/form-builder'
    | '/test/referral-link'
    | '/test/user-list'
    | '/billing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/analytics'
    | '/api-keys'
    | '/articles'
    | '/campaigns'
    | '/contacts'
    | '/deals'
    | '/email'
    | '/main'
    | '/media'
    | '/signin'
    | '/webhooks'
    | '/billing/pay'
    | '/billing/payment_attempt'
    | '/billing/payment_method'
    | '/billing/plans'
    | '/oauth/signedin'
    | '/test/analytics-dashboard'
    | '/test/campaign-card'
    | '/test/email-editor'
    | '/test/form-builder'
    | '/test/referral-link'
    | '/test/user-list'
    | '/billing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ArticlesRoute: typeof ArticlesRoute
  CampaignsRoute: typeof CampaignsRoute
  ContactsRoute: typeof ContactsRoute
  DealsRoute: typeof DealsRoute
  EmailRoute: typeof EmailRoute
  MainRoute: typeof MainRoute
  MediaRoute: typeof MediaRoute
  SigninRoute: typeof SigninRoute
  WebhooksRoute: typeof WebhooksRoute
  BillingPayRoute: typeof BillingPayRoute
  BillingPayment_attemptRoute: typeof BillingPayment_attemptRoute
  BillingPayment_methodRoute: typeof BillingPayment_methodRoute
  BillingPlansRoute: typeof BillingPlansRoute
  OauthSignedinRoute: typeof OauthSignedinRoute
  TestAnalyticsDashboardRoute: typeof TestAnalyticsDashboardRoute
  TestCampaignCardRoute: typeof TestCampaignCardRoute
  TestEmailEditorRoute: typeof TestEmailEditorRoute
  TestFormBuilderRoute: typeof TestFormBuilderRoute
  TestReferralLinkRoute: typeof TestReferralLinkRoute
  TestUserListRoute: typeof TestUserListRoute
  BillingIndexRoute: typeof BillingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/user-list': {
      id: '/test/user-list'
      path: '/test/user-list'
      fullPath: '/test/user-list'
      preLoaderRoute: typeof TestUserListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/referral-link': {
      id: '/test/referral-link'
      path: '/test/referral-link'
      fullPath: '/test/referral-link'
      preLoaderRoute: typeof TestReferralLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/form-builder': {
      id: '/test/form-builder'
      path: '/test/form-builder'
      fullPath: '/test/form-builder'
      preLoaderRoute: typeof TestFormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/email-editor': {
      id: '/test/email-editor'
      path: '/test/email-editor'
      fullPath: '/test/email-editor'
      preLoaderRoute: typeof TestEmailEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/campaign-card': {
      id: '/test/campaign-card'
      path: '/test/campaign-card'
      fullPath: '/test/campaign-card'
      preLoaderRoute: typeof TestCampaignCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/analytics-dashboard': {
      id: '/test/analytics-dashboard'
      path: '/test/analytics-dashboard'
      fullPath: '/test/analytics-dashboard'
      preLoaderRoute: typeof TestAnalyticsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/signedin': {
      id: '/oauth/signedin'
      path: '/oauth/signedin'
      fullPath: '/oauth/signedin'
      preLoaderRoute: typeof OauthSignedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/plans': {
      id: '/billing/plans'
      path: '/billing/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof BillingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/payment_method': {
      id: '/billing/payment_method'
      path: '/billing/payment_method'
      fullPath: '/billing/payment_method'
      preLoaderRoute: typeof BillingPayment_methodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/payment_attempt': {
      id: '/billing/payment_attempt'
      path: '/billing/payment_attempt'
      fullPath: '/billing/payment_attempt'
      preLoaderRoute: typeof BillingPayment_attemptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/pay': {
      id: '/billing/pay'
      path: '/billing/pay'
      fullPath: '/billing/pay'
      preLoaderRoute: typeof BillingPayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiKeysRoute: ApiKeysRoute,
  ArticlesRoute: ArticlesRoute,
  CampaignsRoute: CampaignsRoute,
  ContactsRoute: ContactsRoute,
  DealsRoute: DealsRoute,
  EmailRoute: EmailRoute,
  MainRoute: MainRoute,
  MediaRoute: MediaRoute,
  SigninRoute: SigninRoute,
  WebhooksRoute: WebhooksRoute,
  BillingPayRoute: BillingPayRoute,
  BillingPayment_attemptRoute: BillingPayment_attemptRoute,
  BillingPayment_methodRoute: BillingPayment_methodRoute,
  BillingPlansRoute: BillingPlansRoute,
  OauthSignedinRoute: OauthSignedinRoute,
  TestAnalyticsDashboardRoute: TestAnalyticsDashboardRoute,
  TestCampaignCardRoute: TestCampaignCardRoute,
  TestEmailEditorRoute: TestEmailEditorRoute,
  TestFormBuilderRoute: TestFormBuilderRoute,
  TestReferralLinkRoute: TestReferralLinkRoute,
  TestUserListRoute: TestUserListRoute,
  BillingIndexRoute: BillingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
